In [2]:
import matplotlib.pyplot as plt
import numpy as np

import matplotlib as mpl

In [5]:
import pandas as pd
url = "https://raw.githubusercontent.com/GWC-DCMB/CapstoneProject/master/datasets/"
filepath = "/sleep_study/2014SleepinAmericaPollSleepintheModernFamilyRawDataExcel.csv"
df = pd.read_csv(url + filepath)
df.head()

,CaseID,weight,tm_start,tm_finish,duration,Xspanish,Have children?,How many children?,child age,child gender,...,rules_TV,rules_caffeine,rules_phone,rules_computer/tablet,rules_games,impact_performance,impact_mood,impact_behavior,impact_quality of life,marital status
0,180,0.2520,12/13/13 3:21,12/13/13 3:30,8,1,1,1,16,1,...,3,3,4,3,3,1,1,1,1,1
1,1027,0.9166,12/19/13 6:38,12/19/13 6:58,19,2,1,2,9,2,...,1,1,1,1,1,1,1,1,1,1
2,635,1.3663,12/17/13 21:43,12/17/13 21:53,10,1,1,1,14,1,...,3,4,3,3,2,1,1,2,2,1
3,3,0.4241,12/12/13 22:04,12/12/13 22:16,11,1,1,1,17,1,...,4,4,1,4,1,1,1,1,2,5
4,265,0.6404,12/13/13 13:16,12/13/13 13:25,8,1,1,1,16,2,...,1,4,1,1,4,2,1,2,2,1